#!/bin/sh

cat > tempin <<EOF
        SET XLOC 0
        SET YLOC 0
        SET ONE  1
        printloc    # 0 0 1
RT1     IF  XLOC  >  22  LUP  # farthest to right I want to go
        XMOVE ONE
        ADD XLOC ONE
        GOTO RT1      # keep moving
LUP     printloc    # 23 0 1
LUP1    IF  YLOC  >  22  LT
        YMOVE ONE
	ADD YLOC ONE
	GOTO LUP1
LT      printloc    # 23 23 1
LT1     IF  XLOC < 11    LDN
        XMOVE -1
	SUB XLOC 1
	GOTO LT1
LDN     printloc    # 10 23 1
LDN1    IF YLOC < 11  DONE
        YMOVE -1
        SUB YLOC 1
	GOTO LDN1
DONE    printloc    # 10 10 1
        HALT
EOF

python3.7 ./$1 tempin 

echo
echo "RMB: "
echo    0 0
echo    23 0
echo    23 23
echo    10 23
echo    10 10

rm -f tempin
